import { Translations } from './types';

// Simulated translations data
export const translationsData: Translations = {
  en: {
    en: 'En',
    ru: '',
    welcome: 'Welcome',
    main: 'Editor',
    registration: 'Registration',
    login: 'Sign in',
    logout: 'Sign out',
    registerTitle: 'Create an account',
    registerSubtitle: 'Registered user benefit:',
    registerText: 'Already have an account? Then just click ',
    loginTitle: 'Sign in',
    loginSubtitle: 'Not registered?',
    loginText: 'Creating an account will take no more than a minute ',
    notfoundText: 'Error',
    notfoundTitle: 'Sorry! We could not find what you were looking for. ',
    notfoundInfo: 'The page was not found.',
    notfoundLink: 'Go to home page',
    submit: 'Submit',
    api: 'API',
    headers: 'Headers',
    variables: 'Variables',
    request: 'Request',
    response: 'Response',
    graphqlTitle: ' — this is the ability to harness all the power',
    graphqlText: 'make a request into your own universe',
    graphqlDescr:
      'The task is to implement a playground/IDE for working with GraphQL queries. GraphQL is a query language used by client applications to handle data. GraphQL is associated with the concept of a schema that allows organizing the creation, reading, updating, and deleting of data in the application. GraphiQL is an open-source tool. In addition to the IDE itself for working with GraphQL queries, authorization capabilities are implemented to grant access to the tool only to authorized users. ',
    dogTitle: `Let's do something together!`,
    dogText1: 'Try to use our editor created thanks to the course ',
    dogText2:
      'By taking courses, you get: free training, technological materials, a mentor, new friends, a certificate and much more.',
    dogBtn: 'Go to the editor',
    aboutTitle: 'You get it!',
    plusTitle: 'Advantages',
    plusBtn: 'Go to the editor',
    mainTitle: 'GraphiQL Editor',
    attentionApi: 'Attention! Submitting API...',
    attentionHeaders: 'Attention! Submitting Headers...',
    attentionVariables: 'Attention! Submitting Variables...',
    docsLink: 'Docs',
    ourTeam: 'Our team',
  },
  ru: {
    en: '',
    ru: 'Рус',
    welcome: 'Приветствие',
    main: 'Редактор',
    registration: 'Регистрация',
    login: 'Вход',
    logout: 'Выход',
    registerTitle: 'Создать учетную запись',
    registerSubtitle: 'Преимущества зарегистрированного пользователя:',
    registerText: 'Уже есть учетная запись? Тогда просто жмите ',
    loginTitle: 'Вход',
    loginSubtitle: 'Не зарегистрированы?',
    loginText: 'Создание учетной записи займет не больше минуты. ',
    notfoundText: 'Ошибка',
    notfoundTitle: 'Извините! Мы не смогли найти то, что вы искали.',
    notfoundInfo: 'Запрашиваемая страница не найдена.',
    notfoundLink: 'Перейти на главную страницу',
    submit: 'Отправить',
    api: 'АПИ',
    headers: 'Заголовок запроса',
    variables: 'Переменные',
    request: 'Запрос',
    response: 'Ответ',
    graphqlTitle: ' — это возможность использовать всю мощь',
    graphqlText: 'сделай запрос в свою собственную вселенную',
    graphqlDescr:
      'Задача состоит в том, чтобы реализовать playground/IDE для работы с запросами GraphQL.GraphQL - это язык запросов, используемый клиентскими приложениями для обработки данных.GraphQL ассоциируется с таким понятием, как schema, которое позволяет организовать создание, чтение, обновление и удаление данных в приложении. GraphiQL - это инструмент с открытым исходным кодом.Помимо самого ide для работы с запросами GraphQL, реализованы возможности авторизации, чтобы предоставить доступ к инструменту только авторизованным пользователям. ',
    dogTitle: 'Давайте делать что-нибудь вместе!',
    dogText1:
      'Попробуйте в использовании наш редактор, созданный благодаря курсу от ',
    dogText2:
      'Обучаясь на курсе вы получаете: бесплатное обучение, учебные материалы, ментора, новых друзей, сертификат и многое другое.',
    dogBtn: 'Перейти в редактор',
    aboutTitle: 'Вы получаете!',
    plusTitle: 'Преимущества',
    plusBtn: 'Перейти в редактор',
    mainTitle: 'GraphiQL Редактор',
    attentionApi: 'Внимание! Отправка API...',
    attentionHeaders: 'Внимание! Отправка заголовков...',
    attentionVariables: 'Внимание! Отправка переменных...',
    docsLink: 'Схема',
    ourTeam: 'Наша команда',
  },
};
